### ISSUE TITLE
Mobile usability report

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#42]
![image](https://user-images.githubusercontent.com/312463/64147789-d556f800-ce21-11e9-96b9-11fd3b93daf8.png)

Text too small:
![image](https://user-images.githubusercontent.com/312463/64147814-e6a00480-ce21-11e9-90fc-3443624a7116.png)

Clickable elements too close:
![image](https://user-images.githubusercontent.com/312463/64147825-f15a9980-ce21-11e9-9e7e-a799c0a9802d.png)

Content wider than screen:
![image](https://user-images.githubusercontent.com/312463/64147837-fae40180-ce21-11e9-910c-690b89c1eb7b.png)

**Comment by jparrill** [comment]
Adding more info:

The real error comes because Google Search Console tries to reach [https://metal3.io/2019/04/30/Metal-Kubed-Baremetal-Provisioning-for-Kubernetes.html](https://metal3.io/2019/04/30/Metal-Kubed-Baremetal-Provisioning-for-Kubernetes.html) instead of [https://metal3.io/openshift/kubernetes/metal3/2019/04/30/Metal-Kubed-Baremetal-Provisioning-for-Kubernetes.html](https://metal3.io/openshift/kubernetes/metal3/2019/04/30/Metal-Kubed-Baremetal-Provisioning-for-Kubernetes.html)

The error/s appears because the page cannot be reached, all three errors comes from this one.

**Comment by iranzo** [comment]
Fixed by adding:

permalink: /blog/:year/:month/:day/:title:output_ext

to _config.yml so that all articles have url based on date and not on tags
